### ISSUE TITLE
Album-page only supports album with subalbums, not album with tracks

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#112]
As of now, the route `album/[id]` only supports an album with sub-albums, but not an album with tracks. This became apparent when introducing the `Go to album` option on a track.

Since not every album having tracks has a parent-album, we need a route which can display those. I'd personally prefer to have a route which can deal with both.

@kkuepper Is it in theory also possible to have an album with sub-albums and tracks? Is this possible in the app and should this be possible on the web? For flexibility, I'd prefer to be able to support it, but if it has been taken out of the possible scenarios, it doesn't make sense to force its support.

**Comment by kkuepper** [comment]
https://bmm.brunstad.org/album/91501

do you mean this case where a track is directly under the parent album?

![Screenshot 2023-05-05 at 2 30 29 PM](https://user-images.githubusercontent.com/649978/236539569-3989460d-f478-4fdb-a6b5-26159b9c9529.png)

**Comment by SimonSimCity** [comment]
Just partially fixed by #172, as it only fixes tracks in a sub-album. An album with sub-tracks, or the one mentioned by Karsten still doesn't work.

**Comment by SimonSimCity** [comment]
@julo-web-dev thanks for solving this issue 🎉
