### ISSUE TITLE
View for podcasts

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#132]
On the app, there's almost no difference in viewing podcasts, albums or playlists (curated or private). This could be a first step for the web-version, too. The major addition would be, that the list of tracks can be extended when reaching the bottom of the list of currently loaded items.

This page is needed for the home-screen (#64).

@sclausendk - would be nice to have a short response from you on the design.

**Comment by SimonSimCity** [comment]
It was just to hear from you if its OK to copy the look of playlists or albums without sub-album to podcasts, or if you had something else in mind how it should look...

**Comment by sclausendk** [comment]
Right! Yes! That was the plan all along! :) 
Although, for podcasts, we add separators per week.
