### ISSUE TITLE
Generic DropdownMenu using Headless UI

### ISSUE THREAD

**Issue by sifferhans** [bcc-code/bmm-web#134]
Should we create a generic `DropdownMenu` component using HeadlessUI? I see @bjornarhagen created a nice-looking component for tracks, but they lack keyboard-navigation and focus management and such.

We could make it standardized, but with customiseability via slots.
```vue
<!-- default -->
<script setup lang="ts">
const items = [
	{ label: 'Edit', icon: 'edit' },
	{ label: 'Add to favourites', icon: 'heart' },
	{ label: 'Delete', icon: 'trash' },
]
</script>

<template>
	<DropdownMenu :items="items">
		<button>Open menu</button>
	</DropdownMenu>
</template>
```

```vue
<!-- custom -->
<script setup lang="ts">
const items = [
	{ label: 'Edit', icon: 'edit' },
	{ label: 'Add to favourites', icon: 'heart' },
	{ label: 'Delete', icon: 'trash' },
]
</script>

<template>
	<DropdownMenu :items="items">
		<button>Open menu</button>
		<template #item="{ item }">
			<span>{{ item.label }}</span>
		</template>
	</DropdownMenu>
</template>
```

Johan also is trying to create a dropdown component, and I think solving it once and reusing should be done.

**Comment by SimonSimCity** [comment]
Thanks for providing your idea 😃 Could you please provide some info on which dropdown you specifically are referring to where this could be useful, or provide some typing to the `items` property? 😅 To me it's quite unclear what use-cases you want to cover here ...

**Comment by sifferhans** [comment]
@SimonSimCity Sorry, late answer 😅 The idea is to make a standard way to create dropdown menus, like the menu of tracks:
![CleanShot 2023-08-22 at 11 12 19](https://github.com/bcc-code/bmm-web/assets/18753964/55346252-a7da-4b5d-8c80-b954954cbb66)

This kind of menu is used for tracks, when clicking the profile picture as sketched in Figma:
![CleanShot 2023-08-22 at 11 13 30](https://github.com/bcc-code/bmm-web/assets/18753964/a1b33766-d5f2-43f7-b51d-df15a33be37f)

These menus have similar functionality and visuals, so it would make sense to create a generic `DropdownMenu` component to use as a base for all menus like the ones mentioned.

The `MenuItem` type can be defined if we go for a solution like this

**Comment by SimonSimCity** [comment]
Sounds as too great of a generalist approach, IMO ... If you feel like it and know how to approach it in a way, which makes the code better readable or supports typing better, OK, but this sounds like a lot of things without much value to me. I'd rather focus on the other tasks we have.

I've also thought of specializing the current menu, but as of now I found my time better spent in other things around this project.

**Comment by SimonSimCity** [comment]
If you see a strong need for it, go for it. I'll close the issue, because I wouldn't advice another person to pick it up due to the limited benefit, great potential of a negative performance impact I see and the growing number of tasks we have on this repo.
