### ISSUE TITLE
load private playlists in sidebar

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#14]
[on Figma ](https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?node-id=153-119499&t=fbPmZ93IClCLCkqL-0) you can see that the sidebar shows a list of your playlists.

**Comment by SimonSimCity** [comment]
![Screenshot_20230322-095114](https://user-images.githubusercontent.com/392589/226850061-0d38d8bb-ff9b-4dc5-96b0-81eba507d5a3.jpg)

**Comment by belljohan3** [comment]
Private playlist loaded and push in the feat/private-playlists-in-sidebar branch.. @SimonSimCity  can you review?

**Comment by SimonSimCity** [comment]
Sure. I think we should meet on this; sometimes better to talk through something f2f 😊
