### ISSUE TITLE
integrate a player library

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#15]
- choose a library / build your own library
- setup library and player component
- play file when clicking on a track (potentially hard-code a file url if loading of tracks isn't implemented yet)
- make sure playing a file passes authentication info to server

**Comment by steffanhalv** [comment]
I would first try doing it without a library, I actually do not think a library is necessary.

**Comment by kkuepper** [comment]
> 

Same for me. Adjusted the description.

**Comment by sifferhans** [comment]
We used [plyr](https://plyr.io/#audio) for the SongTreasures web app, but it might not be customizable enough for this case

**Comment by belljohan3** [comment]
@sifferhans if you use that library, it means that we will no longer able to download song from the site ?

**Comment by kkuepper** [comment]
@belljohan3 the player library has no impact on if a song can be downloaded or not. I opened another issue #57 where that can be discussed.

**Comment by belljohan3** [comment]
Okay @kkuepper !
