### ISSUE TITLE
Refresh access token before it expires

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#153]
After the app has been open for more than 24h, I can't play anymore. I'm pretty sure that happens because the access token is valid for 24h and has expired.
As a work-around you can close and reopen the app, which gets you a new access token.

**Comment by SimonSimCity** [comment]
Something which might be helpful here: https://stackoverflow.com/a/66604849/517914

**Comment by SimonSimCity** [comment]
Changed the title because it's not only electron where this needs to be fixed

**Comment by SimonSimCity** [comment]
Should be fixed by #204. If its not, we can reopen this ticket and add some details to it.
