### ISSUE TITLE
load private playlist details

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#16]
- new route for private playlists: bmm-web.brunstad.org/playlist/private/:id
- new view
- load information from Api (GET /track_collection/{id})
- show information in view

**Comment by sifferhans** [comment]
Is there documentation on how to get the private playlists from the API? If so, I could try implementing this

**Comment by kkuepper** [comment]
There's swagger under https://bmm-api.brunstad.org/documentation/index.html .
You would need GET /track_collection/{id}

**Comment by sifferhans** [comment]
Ok nice, I can have a go at it 😊

**Comment by sifferhans** [comment]
@kkuepper Does the `@bcc-code/bmm-sdk-fetch` package have the relevant API methods, or do we need to create a solution locally in the app?

**Comment by kkuepper** [comment]
The package takes the swagger and generates a bunch of code from that.
So it should be pretty easy to do api calls.

**Comment by sifferhans** [comment]
I've created #31 for this

**Comment by belljohan3** [comment]
@sifferhans i have already created a component for private playlist. May be you can just use that to add a private playlist details ??
