### ISSUE TITLE
Previous track button, rewind on first push

### ISSUE THREAD

**Issue by Ghostbird** [bcc-code/bmm-web#176]
Currently the previous track button jumps back to the start of the previous track. Many players instead make the previous track button jump back to the most recent track start. If you press it once, it restarts the current track. If you press it twice, it starts the previous track.

**Comment by SimonSimCity** [comment]
Thanks, I'll add this as part of #102 which is a refactoring of basically most of the player as it is now. [The app uses a threshold of 5 seconds.](https://github.com/bcc-code/bmm-app/blob/develop/BMM.UI.iOS/Application/NewMediaPlayer/IosMediaPlayer.cs#L241) @sclausendk does a 5 second threshold sound good?

**Comment by kkuepper** [comment]
Added in 0.2.9

**Comment by SimonSimCity** [comment]
Added as part of #319
