### ISSUE TITLE
Player: Implement repeat single track

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#186]
The player should have a repeat option, which allows the user to either repeat the currently playing track (single) or the queue.

**Comment by kkuepper** [comment]
repeating the queue has been implemented in the meantime.
Only thing left is repeating single track.

Icon can be found in [Figma](https://www.figma.com/file/b15RtXovfukzh6uJxFsQPs/Bmm-%E2%80%93-Design-System?type=design&node-id=43-0&mode=design&t=9od1brd4KLkES4pH-0)

**Comment by SimonSimCity** [comment]
Implemented in #366
