### ISSUE TITLE
Profile dropdown invisible in dark mode

### ISSUE THREAD

**Issue by Ghostbird** [bcc-code/bmm-web#188]
I had not even realised it was there. I clicked the right spot accidentally today, and it opened:
![image](https://github.com/bcc-code/bmm-web/assets/1202149/77f326c0-3b32-4541-a3b9-6bcef9be060c)
As you can see, the text does seem to follow dark mode, but the background doesn't so even once it's open, you can only read the highlighted entry that the mouse pointer is hovering. Even that, doesn't work for the (three?) entries below the first separator line.
This bug is in release `v0.0.3`

**Comment by SimonSimCity** [comment]
Fixed by #206
