### ISSUE TITLE
Section cannot be scrolled horizontally without a trackpad

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#191]
![Screenshot 2023-08-16 at 10 07 07](https://github.com/bcc-code/bmm-web/assets/392589/2cc002e3-5ff3-414b-9020-6d0877aef4e9)

@sclausendk What would be a good way here? In #141 the horizontal scroll bar was hidden away, so a user who does not have a trackpad, but just a mouse with a vertical scrolling wheel is unable to scroll horizontally. How should we tackle this issue?

**Comment by sifferhans** [comment]
We could maybe have navigation buttons on each side of the slider?

**Comment by sclausendk** [comment]
I'll fix this today.
I do not think that we should have sliders.
We should rather show a fixed number of items and have a "See all" button to see a grid with all of them.
Added designs for Home screen and see all here:
https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?type=design&node-id=1004-5327&mode=design&t=C1OFoO4SaSTXt7mh-11

**Comment by SimonSimCity** [comment]
Will be fixed in the course of #194
