### ISSUE TITLE
Player UI: Highlight colour is not suitable for dark mode

### ISSUE THREAD

**Issue by Ghostbird** [bcc-code/bmm-web#214]
As shown in the image below, the chosen highlight has too low contrast with the white text in the dark mode. We'll need a dark-mode suitable highlight colour.

![image](https://github.com/bcc-code/bmm-web/assets/1202149/c16795bb-fcab-4130-b763-f045c0a45fa5)

Additional considerations:

- The side menu uses a _different_ highlight colour. Is the player UI highlight intentionally different?
- Instead of changing the highlight colour, the text might be changed to match the background colour instead, the way this also happens in the side menu.

**Comment by Ghostbird** [comment]
I've taken the liberty to add the "good first issue" label, since I _assume_ this will be a relatively small and easy to fix thing. If I'm mistaken, it can be removed.

**Comment by kkuepper** [comment]
@SimonSimCity Shouldn't have good first issue since someone needs to decide what color to take. Someone new can't do that.

**Comment by SimonSimCity** [comment]
Has been fixed as part of #227
