### ISSUE TITLE
Fix login on auto-deployed environments

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#22]
Currently, the github-actions bot deploys every PR to Azure Static Web Apps. Those are actually currently not useful as the login fails with an unidentified error in which the service asks you to log in again. I guess this is a problem which has to do with the domain this is hosted on. Would be nice to see this fixed or removed from the github-actions.

**Comment by kkuepper** [comment]
This is now working.
The url has the following format.
https://salmon-pebble-009136d03-{id-of-pull-request}.westeurope.2.azurestaticapps.net/
