### ISSUE TITLE
This with capacitorjs might be better than bmm-C#?

### ISSUE THREAD

**Issue by kklem0** [bcc-code/bmm-web#23]
If your web already consider to be used on mobile then it would be nice to keep capacitorjs or tauri in mind from the start?
Is there something technical the c# version can do but vue version cannot?

**Comment by kkuepper** [comment]
If we wanted to replace bmm-app we would probably use Flutter.
Vue is optimized to build web-apps fast but isn't optimized for a good mobile experience.
