### ISSUE TITLE
Setup Nuxt plugin for Plausible (Analytics)

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#237]
https://github.com/nuxt-modules/plausible

<script defer data-domain="bmm-web.brunstad.org" src="https://plausible.io/js/script.js"></script>

**Comment by BeastiW** [comment]
I added the Nuxt plugin in the configuration and the package.json - now we could start adding custom events like e.g. `useTrackEvent("shuffle");`
