### ISSUE TITLE
Smaller installable (428MB -> ~100MB)

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#238]
The install packages are pretty big right now. (Mac: 428MB, Windows: 174MB). On Mac the unzipped file in /Applications is 1.19GB.
See https://github.com/bcc-code/bmm-web/releases

We should get the size down significantly. I wonder if we pack files that are only needed during build as well.

**Comment by SimonSimCity** [comment]
Does #246 fulfill our requirements here, or do we need further research?

**Comment by kkuepper** [comment]
@SimonSimCity The package sizes are now ~100MB and that's what's reasonable to expect when using Electron. If we want it smaller we'd need to look at Tauri or similar. But I think for the next year or 2 we have a lot more pressing issues than that.


<img width="522" alt="Screenshot 2023-11-19 at 8 54 33 AM" src="https://github.com/bcc-code/bmm-web/assets/649978/640a18c6-41cf-4526-b988-ecbaf1862555">
