### ISSUE TITLE
Popup for Track details / More information

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#239]
- [x] Implement component for modal/popup
- [x] fill popup with information about the track ([see Figma](https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?type=design&node-id=801-26347&mode=design&t=uI8D4WpY5cQpD42J-0))
- [x] make links work (when clicking on 3 dots)

#240 also needs the popup component. Therefore it should be implemented as a separate PR that gets merged quickly.

![Screenshot 2023-11-17 at 2 34 33 PM](https://github.com/bcc-code/bmm-web/assets/649978/368da0b9-6fc2-421f-bd69-af969b3c87e0)

**Comment by SimonSimCity** [comment]
Open questions:
- [ ] Which types of references do we have?
- [ ] What locale should we use to show the published-at date? Is the locale of the current environment good enough, or should we use something related to the chosen language?

About references ... Maybe it's good to update the API to have a better typing here. There seems to be some kind of enum-type per relation of a track (https://github.com/bcc-code/bmm-api/blob/develop/BMM.Api.Core/DatabaseContract/RelationType.cs#L10) but its not typed, excepted for some typings I found (https://github.com/bcc-code/bmm-api/blob/develop/BMM.Api.Core/DatabaseContract/Track.cs#L216-L278). @kkuepper Would be good to know if its any good to improve the api here or whether at all its possible to prove that's even possible.

**Comment by kkuepper** [comment]
About locale:
The current website uses "5. Jan 2024 - 14:26" which is the european version. I think it's fine to keep doing that. Do whatever is easy to do.

About references:
I'm not sure what you want from me. It sounds like the typing doesn't work properly so we need to fix it. But you (@SimonSimCity) usually do that.

**Comment by SimonSimCity** [comment]
Fixed by https://github.com/bcc-code/bmm-api/pull/480, https://github.com/bcc-code/bmm-api/pull/485 and https://github.com/bcc-code/bmm-web/pull/301
