### ISSUE TITLE
Add BMM design tokens to tailwind config

### ISSUE THREAD

**Issue by sifferhans** [bcc-code/bmm-web#24]

**Comment by SimonSimCity** [comment]
Wasn't this handled or at least supposed to be in #20 ..? 😅

**Comment by sifferhans** [comment]
@SimonSimCity Sorry, should have provided a description 😅 I meant setting up the design system. The Figma design has defined colors and fonts that probably should be added to the config.

Eg. adding a `primary` color, so we can do `bg-primary` instead of `bg-lime-300` or whatever.

**Comment by steffanhalv** [comment]
Søren will said he could send me the design tokens, then I can set it up 👍🏼

**Comment by steffanhalv** [comment]
I added a PR which contains the tokens, but I have not got any time to implement it. Feel free if anyone want to do the rest of the job 😊. Ref. #73

**Comment by sifferhans** [comment]
I can look at it!
