### ISSUE TITLE
Settings Popups

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#240]
- [x] add component for model/popups
- [x] look at [Figma](https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?type=design&node-id=153-127573&mode=design&t=uI8D4WpY5cQpD42J-0)
- [x] popup for Theme selection
- [x] popup for Interface language
- [x] style interface language selection
- [x] implement content language selection
- [x] persist selected settings

#239 also needs the popup component. Therefore it should be implemented as a separate PR that gets merged quickly.

![Screenshot 2023-11-17 at 2 38 35 PM](https://github.com/bcc-code/bmm-web/assets/649978/d0c1ee8e-7e11-43a4-9c02-c94a8a6d4c2b)

**Comment by kkuepper** [comment]
Would be nice if someone else can do the remaining 2 tasks

**Comment by sifferhans** [comment]
@kkuepper I can try fixing the last two tasks.

Another point: we should probably make the dialog component more accessible. We should constrain tabbing inside the dialog when open to make it easier to navigate with a keyboard.

**Comment by SimonSimCity** [comment]
@sifferhans Feel free 😎  I've just done something because we needed something, but I wasn't putting a lot of effort into it.

**Comment by sifferhans** [comment]
@SimonSimCity I've created a draft PR where I change to using the Headless UI Dialog component as a base 😊 #256

**Comment by sifferhans** [comment]
@kkuepper Is the image you attached the way it should be designed? Both language settings in the same dialog?

**Comment by kkuepper** [comment]
@sifferhans The figma isn't exactly clear. I think Søren explored different ideas but didn't decide on one.
My thought was to make separate dialogs, that each pretty much look like the in the image above.
Do as feels natural to you and we might change it if Søren doesn't like it.
