### ISSUE TITLE
Title of the website

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#260]
There was already a small start by @sifferhans in the PR #258, which I asked him to roll back.

This ticket is first and foremost to create a concept of what should be the title of the website at any given time. @sclausendk, I think you should have a good first start in this discussion.

At the moment, the title is fixed to `BMM`.

**Comment by sclausendk** [comment]
In general:
Pages for browsing: "Bmm – [Page name]" i.e.: "Bmm – Home"
Albums / Playlists / Events: "Bmm – [Collection Title]" i.e.: "Bmm – Søstrestevnet 2020"

Are there other cases that needs to be solved?

**Comment by sclausendk** [comment]
This looks great :)

**Comment by SimonSimCity** [comment]
@sclausendk Since some requests already contain a title for the page, I've used that instead. Here's the full list of what #373 contains. The remaining should be implemented when their content is done.

Every title is prefixed with "BMM - ". If the title (for whatever reason) is empty, it's set to "BMM".

| Route   |     Title |
| --------|-----------|
| pages/[...error] | t("Unknown route") |
| pages/album/[id] | album.title ?? t("Album") |
| pages/archive | -not implemented- |
| pages/audiobooks | data.title ?? "" |
| pages/browse/audiobooks | data.title ?? "" |
| pages/browse/events | data.title ?? "" |
| pages/browse/index | t("Browse") |
| pages/browse/music | data.title ?? "" |
| pages/browse/podcasts | data.title ?? "" |
| pages/contributors | t("Contributors") |
| pages/copyright | t("Copyright") |
| pages/daily-fra-kaare | -not implemented- |
| pages/featured | data.title ?? "" |
| pages/index | t("Home") |
| pages/music | t("Recent music") |
| pages/playlist/contributor/[id]/[...name] | contributor.name ?? t("Contributor") |
| pages/playlist/contributor/[id]/index | contributor.name ?? t("Contributor") |
| pages/playlist/curated/[id]/[...name] | playlist.title ?? t("Playlist") |
| pages/playlist/curated/[id]/index | playlist.title ?? t("Playlist") |
| pages/playlist/latest | -not implemented- |
| pages/playlist/podcast/[id]/[...name] | podcast.title ?? t("Podcast") |
| pages/playlist/podcast/[id]/index | podcast.title ?? t("Podcast") |
| pages/playlist/private/[id]/[...name] | collection.name ?? t("Playlist") |
| pages/playlist/private/[id]/index | collection.name ?? t("Playlist") |
| pages/playlist/search/[...term] | t("Search") |
| pages/playlist/shared/[sharingsecret] | -not implemented- |
| pages/search/[[term]] | t("Search") |
| pages/speeches | t("Recent messages") |
| pages/track/[id]/[...language] | album.title ?? t("Album") |
| pages/track/[id]/index | album.title ?? t("Album") |
| pages/year-in-review | -not implemented- |

**Comment by kkuepper** [comment]
Personally I prefer to have BMM first. But looking at other websites (Figma, Google, Microsoft Azure, ...), it's commonly done with BMM at the end. So I suggest doing the same.

**Comment by sifferhans** [comment]
Yeah, we probably want to have the most important information _(title of track etc)_ so it is easier to identify for users eg. when BMM is in another browser tab.

It is probably more useful to see 
![CleanShot 2024-08-29 at 12 24 34](https://github.com/user-attachments/assets/40642468-1d14-4def-a4f2-77d71a763c13)

than it is to see
![CleanShot 2024-08-29 at 12 24 55](https://github.com/user-attachments/assets/1864beee-7180-488f-8588-f65e135493c9)
