### ISSUE TITLE
Align `TrackItem` design to Figma

### ISSUE THREAD

**Issue by sifferhans** [bcc-code/bmm-web#263]
The track items in the app are not correctly aligned to each other; it should be more table-like, with consistent column widths and alignment throughout the rows.

I would think this could be a nice use case for CSS subgrid. Or just using `<table>` 🤪

https://caniuse.com/css-subgrid

## Figma
![CleanShot 2023-12-07 at 15 08 49](https://github.com/bcc-code/bmm-web/assets/18753964/454a14e0-422c-46d8-a3ef-207fb4531358)

## App
![CleanShot 2023-12-07 at 15 10 14](https://github.com/bcc-code/bmm-web/assets/18753964/7d52d2fe-ff7a-4ec0-bbb0-b2ef8883d6f8)

**Comment by SimonSimCity** [comment]
@sifferhans I'd say it's worth a try to go for css-subgrid 😎 when hiding all browser versions used by <0.5% most of those which do not support it are gone 🤗

**Comment by BeastiW** [comment]
Hi @SimonSimCity @victorienfotsing

I tried to convert it to grid/ subgrid - I thought this was an interesting task.
Please have a look at this branch: https://github.com/bcc-code/bmm-web/tree/263-alignTrackItem-Design

I guess I need some help concerning two points:

The mouseover on simple tracks is not working any more. When I left the empty div "position: abolute" inside the track item, the click event only played the last track in the list... somehow the div spanned too much space or the layer of the click event is not set properly.
to extend tailwind.conf.ts I had to extend of "figma2tailwind" template in convertToTailwind.ts (maybe this is corrent but it seems dirty).

**Comment by SimonSimCity** [comment]
@BeastiW When having a proposal, please create a draft-PR next time. I've now done it for you, but would be nice to have your input straight there. Now it looks as if it would've been done by me...
