### ISSUE TITLE
shuffle podcast tracks

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#283]
- [x] implement shuffle (load from server since podcasts have 1000+ tracks and the client shouldn't load all of them)
- [x] remove follow button (doesn't make sense without push notifications and automatic downloads)

Edit Bastian:
- [x] implement play button

**Comment by BeastiW** [comment]
I just added a button to load the shuffle request into the player for now - it should be enough for the first release. Tell me if I'm wrong
