### ISSUE TITLE
change language of currently playing track

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#285]
- [x] hide button if only one language is available (e.g. songs)
- [x] show list of available languages from track.languages
- [x] Languages from Profile should be listed first followed by separator. If it's more than 5 languages, hide the others behind the Show all button.
- [x] load track from server with selected language as Accept-Language header
- [x] replace currently playing track with newly loaded one

Probably requires changes to how requests are sent to allow customizing the Accept-Language for a single request.

![Image](https://github.com/bcc-code/bmm-web/assets/649978/95bf825f-d8dc-48a8-8dcd-bafc59ec9fc2)

**Comment by BeastiW** [comment]
created #313 to solve this issue. Discovered that the general approach (reloading all of the content) is much easier. Please comment @kkuepper
