### ISSUE TITLE
go to contributors

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#289]
- [x] read contributors from track.contributors
- [x] Add button for each contributor. e.g. "Go to Kåre J. Smith", "Go to Dag Helge Bernhardsen"
- [x] navigate to "/playlist/contributor/{contributorId}"

**Comment by philipdalen** [comment]
@kkuepper do we have a design for this?

**Comment by kkuepper** [comment]
The design is already implemented. It just doesn't do anything.

<img width="321" alt="Screenshot 2024-02-09 at 6 55 34 PM" src="https://github.com/bcc-code/bmm-web/assets/649978/c43b37df-6612-4429-ab71-b06e58f14fa6">
