### ISSUE TITLE
load more / endless scrolling

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#290]
see https://bmm-web.brunstad.org/playlist/podcast/55 or https://bmm-web.brunstad.org/browse/events

when scrolling to the end of the list, it should load the next items.

**Comment by sifferhans** [comment]
I can give this a try.

**Comment by kkuepper** [comment]
That would be awesome. I don't really know where to start.
`useInfiniteScroll` looks like it's worth a try.

`DocumentList.supportsPaging` is intended to tell you if that list has additional pages.

**Comment by sifferhans** [comment]
@kkuepper I'm gonna have to unassign myself here, as I don't have time to work on this; at least until after the Eastercamp 😅

**Comment by kkuepper** [comment]
> @kkuepper I'm gonna have to unassign myself here, as I don't have time to work on this; at least until after the Eastercamp 😅

Thanks for letting us know
