### ISSUE TITLE
Responsive Tiles

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#300]
As can be seen in Figma the size of the tiles should be responsive.
They should basically always fill the whole screen and move into the 2nd row if necessary. I wonder if they need to be converted from flex into a grid.

https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?type=design&node-id=1004-5340&mode=design&t=sCOId7kOORPF0Oym-0

**Comment by belljohan3** [comment]
Hei @kkuepper 

I would like to go for this task but i am really understand what we must do about the titles ! Can you please explain more ? 

Thanks

**Comment by belljohan3** [comment]
![image](https://github.com/bcc-code/bmm-web/assets/50105980/5f565cdb-b8fb-4ac8-93e5-635c78aa4b0b)

**Comment by SimonSimCity** [comment]
@belljohan3 a tile should span over 50% of the content width; if the content width is smaller than a certain width, the design should adjust to one tile per row, than spanning over the full width.

Does this explain it? 🤗
