### ISSUE TITLE
Type-safe routing

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#32]
Type-safety in routing is not yet enforced on compile time but will fire at runtime (https://github.com/bcc-code/bmm-web/pull/30/files#diff-5248fb6c191afd8d3817ebc00d753089feebefdeaa82ca87a9ef650d780b0a69). A common solution could be to allow a string as property (https://github.com/bcc-code/bmm-web/pull/31/files#diff-65ad36667557ee8e81f651e0dd916ef90edc8deb36ad845cc862a6cfe3d2a805) which also is not desirable as we want to do the parameter validation before loading the component.

A desirable outcome of this task is a way in which we can load components on routes in a type-safe manner which is enforced on build- or compile-time. Components should have the possibility to define the properties as they want (allowing other types next to `string`).

**Comment by sifferhans** [comment]
[vue-router har an experimental feature for this](https://router.vuejs.org/guide/advanced/typed-routes.html), but it might be too sketchy to implement this while it's experimental

**Comment by sifferhans** [comment]
Did you get this working? @SimonSimCity

**Comment by SimonSimCity** [comment]
@sifferhans see #88
