### ISSUE TITLE
blocked autostart breaks player

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#328]
- [ ] If the browser blocks autoplay, I can hit play myself (right now nothing happens)

The browser blocks the player from starting without any user interaction (to prevent websites being annoying). The old website has the same problem. I think Google added that in 2019 or so.

For chrome it depends on the media engagement rate. If you use any media more than 30% of the sessions it's allowed. See [chrome://media-engagement/](chrome://media-engagement/) to check your values.

The issue right now is that you can't just press play since the player is in an invalid state.

_Originally posted by @kkuepper in https://github.com/bcc-code/bmm-web/issues/317#issuecomment-1964109956_

Most likely localhost:9001 will have a high engagement rate. To test if it's working on your local Chrome, you can open a guest profile in Chrome, which should have a low engagement rate.

**Comment by SimonSimCity** [comment]
Just some links for additional information:
* https://developer.chrome.com/blog/autoplay
* https://www.chromium.org/audio-video/autoplay/
* https://support.mozilla.org/en-US/kb/block-autoplay
* https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome
