### ISSUE TITLE
Cannot read properties of undefined (reading 'json')

### ISSUE THREAD

**Issue by kboek** [bcc-code/bmm-web#337]
When opening playlist "Daily Mix", the main window shows an error message `TypeError: Cannot read properties of undefined (reading 'json')`. The message doesn't go away even when you navigate to other items from the left pane. The only thing that helps is closing and re-opening the application

MacOS Sonoma 14.2.1
![Screenshot 2024-03-02 at 10 47 58](https://github.com/bcc-code/bmm-web/assets/743501/149a26d5-510c-43e4-922a-d8569014e288)

**Comment by SimonSimCity** [comment]
Seems like the system failed while trying to report an error. This should be fixed in #343.

**Comment by kkuepper** [comment]
fixed in v0.3.2
