### ISSUE TITLE
User cannot see who actually is logged in.

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-web#361]
A user cannot see whether its him or another person who is logged in. This becomes problematic on shared devices.

The current website solves this issue by using [the topbar](https://developer.bcc.no/bcc-widgets/widgets/topbar.html).

**Comment by SimonSimCity** [comment]
Issue might be linked to #360...

**Comment by kkuepper** [comment]
<img width="138" alt="Screenshot 2024-04-17 at 10 56 51 AM" src="https://github.com/bcc-code/bmm-web/assets/649978/b9de66ce-6968-4092-a8eb-7aa009807739">

This is not enough? But I guess most people don't have a profile picture.
Maybe we could show the initials if no picture is set.

**Comment by SimonSimCity** [comment]
... and show the full name on hover. Might just need another option to show it on a device which doesn't support hover (e.g. surface). Showing the name in the dropdown which opens clicking on the profile is also sufficient to me. Just some place I can see the full name.

**Comment by sifferhans** [comment]
We could also replace the "Profile" text with the name. Maybe less obvious that you can click it that way, but I think it is quite a normal pattern

**Comment by sifferhans** [comment]
@kkuepper @SimonSimCity Here are a couple of ideas:

![CleanShot 2024-06-24 at 15 27 32@2x](https://github.com/bcc-code/bmm-web/assets/18753964/48b64e84-7f1a-4a53-9774-6e4f3e83a0bd)

![CleanShot 2024-06-24 at 15 29 06@2x](https://github.com/bcc-code/bmm-web/assets/18753964/cc617640-f26e-4cac-a0c2-c37d8e2d83e5)

I kinda like the first one better aesthetically

**Comment by kkuepper** [comment]
Another option would be to change the "Sign out" button to "Sign out Sigve Hansen".

@sclausendk Do you want to make a design or should we just decide?

**Comment by sclausendk** [comment]
I'll come up with a design.

**Comment by sclausendk** [comment]
> @kkuepper @SimonSimCity Here are a couple of ideas:
> 
> ![CleanShot 2024-06-24 at 15 27 32@2x](https://private-user-images.githubusercontent.com/18753964/342354589-48b64e84-7f1a-4a53-9774-6e4f3e83a0bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTk1OTgsIm5iZiI6MTcxOTI1OTI5OCwicGF0aCI6Ii8xODc1Mzk2NC8zNDIzNTQ1ODktNDhiNjRlODQtN2YxYS00YTUzLTk3NzQtNmU0ZjNlODNhMGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIwMDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNzU3ODI3NTBhNzQ5NDY4ZmZkNDM4YmEwNzllZmNlOTVmZDBlOTA1OWEzNGUxODBjZTAwMTc2MjBhM2FlNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tI3bTMg8a9rago5RlBFb0V9GtsIo_-cdGPCj4NwWEPE)
> 
> ![CleanShot 2024-06-24 at 15 29 06@2x](https://private-user-images.githubusercontent.com/18753964/342355073-cc617640-f26e-4cac-a0c2-c37d8e2d83e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNTk1OTgsIm5iZiI6MTcxOTI1OTI5OCwicGF0aCI6Ii8xODc1Mzk2NC8zNDIzNTUwNzMtY2M2MTc2NDAtZjI2ZS00Y2FjLWEwYzItYzM3ZDhlMmQ4M2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDIwMDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NGQ5NDQ4NTZiYjM5MmNiOWI5YTYwMzIyNWQ2YjkzYjg3MmM5MDFhZmIzZGU1OWQzOWEzNzZkY2QxODg4NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qge9Zl2j1m2YUyxhV-wl4TIZ9T023xubNS2gFWjw_HU)
> 
> I kinda like the first one better aesthetically. I just use `user.username` from the `useUser` composable for now, but it might be better to have a name instead of the email.

I really like the first one, but we should emphasize the name, and have the email as secondary.

@sifferhans If you switch the styling around, so the first line of text is emphasized, and then change that line to being the Name, we should be good 👍 
Does that make sense?

**Comment by sifferhans** [comment]
@sclausendk More like this?

![CleanShot 2024-06-24 at 22 21 12@2x](https://github.com/bcc-code/bmm-web/assets/18753964/e9def838-bc43-42b3-8934-e4e12457c6e9)

**Comment by sclausendk** [comment]
@sifferhans Spot on! 👏🏼

**Comment by sifferhans** [comment]
@kkuepper Then we need access to the users name somehow. The `UserModel` we get from the SDK only contains the username, which is the email in this case.

**Comment by sifferhans** [comment]
@sclausendk Would it also make sense to move the "Sign out" button closer to the user information? Kinda makes sense in my mind to put these closer to each other as they are quite related.

![CleanShot 2024-06-25 at 15 40 34@2x](https://github.com/bcc-code/bmm-web/assets/18753964/517c3da7-a482-4d07-b558-43705a00743e)

Might be easier to accidentally click it then, though

**Comment by kkuepper** [comment]
Auth0 provides the Display name and email address (see #467 or [temporary build](https://kind-meadow-01b17e903-467.westeurope.3.azurestaticapps.net/).

**Comment by sclausendk** [comment]
@sifferhans I think that makes sense. But the hierarchy becomes a bit unclear.
I would suggest something like this:
<img width="901" alt="image" src="https://github.com/bcc-code/bmm-web/assets/32878631/0148f10d-694c-4bff-8a9b-ade7cbed65e8">

Although this might not scale well with long names, and certain languages (Sign out, Logg ut, Cerrar la sesión, Abmelden, Disconnettersi).

**Comment by SimonSimCity** [comment]
... and keep in mind that names sometimes are quite long, and mail addresses too...

**Comment by sclausendk** [comment]
@SimonSimCity Agree. But keep in mind that seeing 90% of your email address, is enough to identify which user you are on :) I think the above will work well for 95% of all names and emails.
