### ISSUE TITLE
Windows: Microsoft Defender SmartScreen message

### ISSUE THREAD

**Issue by leo-schick** [bcc-code/bmm-web#378]
When opening BMM the first time on Windows one gets this message from Microsoft Defender SmartScreen:

![image](https://github.com/bcc-code/bmm-web/assets/67712864/cba175a2-a03a-4ad4-98d1-4596b31d5c2f)

This should be fixed.

**Comment by kkuepper** [comment]
@KillerX @cs1m0n 
Maybe we should just pay for an EV certificate. [CheapSSL](https://cheapsslsecurity.com/fastssl/ev-code-signing-certificate.html) offers one for ~300 USD per year.
If we do that, one problem is how to handle the token. It's usually put on a physical USB dongle, but apparently there's also a way to put it into AWS KWS.

**Comment by KillerX** [comment]
@kkuepper we have approval for this already (discussion on some other ticket). We also want the same thing for Bible Kids - Explorers. You wanna fix it or want me to take a look?

**Comment by kkuepper** [comment]
thanks to @cs1m0n and @KillerX this has now been completed.
@leo-schick can you test if it works as expected?

**Comment by leo-schick** [comment]
@kkuepper nope, not fixed:

![image](https://github.com/bcc-code/bmm-web/assets/67712864/66b05f54-fb7a-4bdb-b9ad-52137d91bb5c)

**Comment by kkuepper** [comment]
@leo-schick I believe you downloaded the zip file.
We're only signing the [Setup.exe](https://github.com/bcc-code/bmm-web/releases/download/v0.9.1/BMM-Setup-0.9.1.exe).
You can also download through https://bmm.bcc.media/download.
