### ISSUE TITLE
Design: dynamic cover size

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#416]
Currently the covers (ItemCard in code) have a fixed size of 208px. But as shown in Figma, the size is supposed to be flexible (158px - 250px) based on how much space there is.
CSS Grid sounds like a good solution (see branch feature/dynamic-cover-size) but it doesn't allow to only show 1 row of items.
I believe that it can't be solved with CSS and we need some kind of Javascript.

**Comment by andreasgangso** [comment]
I think an autofit grid makes sense to make this like you said
<img width="580" alt="image" src="https://github.com/bcc-code/bmm-web/assets/727125/e443ac12-c983-47c5-bd94-e148dd1ec244">

but when you say you can't show "one row", are you talking about this view on the home page?
<img width="285" alt="image" src="https://github.com/bcc-code/bmm-web/assets/727125/c6e8d8ed-b479-44c3-acc3-3f552de5be3d">

I think that should just be treated as a different view entirely, or use max-height to hide the items (like it's doing today).

**Comment by kkuepper** [comment]
I can't use max-height if the height is dynamic

**Comment by sifferhans** [comment]
> I can't use max-height if the height is dynamic

Couldn't `max-height: max-content` or `min-content` work here?
