### ISSUE TITLE
Add Toolbar

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#43]
- Add toolbar that stays fixed at the top
- has button for profile
- has a title that can be controlled from sub pages
- has a back button (see Lists or Track collections in [Figma](https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?node-id=153-119499&t=wPoh7jyW63RcYqyk-0))
- has a blur for content hidden under it (optional, can be done in a later issue)

<img width="950" alt="Screenshot 2023-03-25 at 9 57 38 AM" src="https://user-images.githubusercontent.com/649978/227721717-1403e94c-a7d2-4612-b6a1-fea2344352d0.png">

<img width="594" alt="Screenshot 2023-03-25 at 10 01 34 AM" src="https://user-images.githubusercontent.com/649978/227721845-577b805e-a830-4967-81fe-bb47a80408a8.png">

**Comment by sifferhans** [comment]
I can take a look at it 😊
