### ISSUE TITLE
component for list of tracks

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#48]
- https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?node-id=153-127571&t=T9N4X3B1t4wCGAvo-0
- show cover, title, song number, Artist and subtype

**Comment by belljohan3** [comment]
Hello @kkuepper can you please post a screenshot in the comments ?

**Comment by belljohan3** [comment]
Hello @kkuepper 
cc: @SimonSimCity 
i think that we don't need this anymore because it has been already implemented as we move to Nuxt. That's why i closed the issue. If i am wrong, please let me know ! 
Thanks
