### ISSUE TITLE
add simple search

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#49]
- We don't have a design yet
- search box
- show list of different items (track, album, playlist, contributor)

**Comment by sifferhans** [comment]
Which of these is the correct one for this?

![Image](https://user-images.githubusercontent.com/18753964/233856857-c5fc89b5-eecc-4b8c-8f8c-08993cae1e17.png)

**Comment by kkuepper** [comment]
Good point.
Search/v2

**Comment by belljohan3** [comment]
Hei @kkuepper. Where should we put the input search ? On the home page ?

**Comment by kkuepper** [comment]
There's a menu entry for search.

<img width="963" alt="Screenshot 2023-07-10 at 8 24 43 AM" src="https://github.com/bcc-code/bmm-web/assets/649978/46223b3f-5eb2-4837-abf5-ba6ac668e8dd">

**Comment by belljohan3** [comment]
Ok thanks so much.
