### ISSUE TITLE
BMM dashboard on bmm web

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bmm-web#507]
A dashboard for BUK mentors to follow along the stats of FRAK engagement

highlight the church of the current user
simple excel feature e.g. sorting, filtering

**Comment by sifferhans** [comment]
@kkuepper Do you have a link to the Excel file? Or maybe a screenshot?

**Comment by sifferhans** [comment]
@kkuepper Do you have a spec for what data we specifically want to display, like what types of columns in the table? Is it exactly as the excel file, or does anything differ?

I guess a better question would be: what information do we want the users to get out of the dashboard / statistics?

**Comment by sifferhans** [comment]
Cannot do much more until backend is ready.
I've set up the basic page, created a simple sortable datatable and made it ready to continue once I have data coming from the API

![Image](https://github.com/user-attachments/assets/498f50db-427b-4e1c-84e2-ce33cc2ae400)

**Comment by sifferhans** [comment]
https://github.com/user-attachments/assets/e68743d5-bf78-4ba6-aff1-3925f82ef78d

**Comment by sifferhans** [comment]
Time-based data remains
