### ISSUE TITLE
maintain Lyrics on bmm-web

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#525]
- [x] list existing lyrics
- [x] CRUD for lyrics
- [x] use [tiptap](https://tiptap.dev/docs/examples/basics/default-text-editor) to edit verses
- [x] Combosearch for contributors
- [x] have useful placeholders to educate people on how it should be used (Verse 1, Chorus)

**Comment by sifferhans** [comment]
@kkuepper Have you created a lyrics-manager role?

**Comment by sifferhans** [comment]
Draft PR here https://github.com/bcc-code/bmm-web/pull/527
