### ISSUE TITLE
Downloading mp3 files

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#57]
Should it be possible to download mp3 files or is it enough to make it offline accessible in the app?

As BCC we see some risks with enabling downloading, since it makes it really easy to download and redistribute our content. Wrongful use of speeches and testimonies can harm both BCC and individuals.

We're evaluating different options:
1. Disable download completely
2. Disable download for everything except Playbacks, Instrumental songs and songs used by Sunday Schools
3. Only enable download for specific user groups (Make music responsible, choir / music leaders, kids mentors, media responsibles, youth leaders, ...)

For BMM Web it means we will wait a bit with implementing downloading and focus on other features first.

**Comment by belljohan3** [comment]
Downloading everything for me would be the best option. For example here in Africa, we don't have often Internet or best quality. It would be nice if we can download everything 😉

**Comment by kkuepper** [comment]
There are 2 interests that need to be balanced:
- make it as easy as possible to use everything
- limit the harm that bad actors can do by making it difficult

We're not talking about making files offline accessible. We're mainly talking about downloading the mp3 file through the website that we want to limit (I also updated the original issue to make that more clear). What are legitimate use cases where people in Africa need to use the mp3 files directly?

**Comment by belljohan3** [comment]
Here in Africa, I think we need accredited MP3 files. I mean that when you upload a file to BMM, you can see the information in the properties of the file. For example, the Copyright, author and others. That's what I think.

**Comment by belljohan3** [comment]
Here in Africa, I think we need accredited MP3 files. I mean that when you upload a file to BMM, you can see the information in the properties of the file. For example, the Copyright, author and others. That's what I think.

**Comment by kkuepper** [comment]
Update: We decided to no longer allow downloading of messages. Fra Kåre and songs can still be downloaded (for now).
