### ISSUE TITLE
design for player

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#65]
- [x] make expanded player fill right side of the screen (available space for content is reduced)
- [x] Animate playing icon in queue (blocked due to missing design from Søren)
- [x] Implement transition (see prototype)
- [x] Marquee for the meta-data
- [x] Let user drag the progress-bar on mouse-down, update the time while keeping the song playing, and update the players position only on mouse-up. (Moved to #305)

a lot has already been implemented. Those 5 tasks are what's left.

- demo: https://www.figma.com/proto/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?node-id=488-16188&scaling=min-zoom&page-id=488%3A16147
- figma: https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?node-id=488-16188&t=uTTeaIsiJ23rNNzX-0

![Image](https://user-images.githubusercontent.com/649978/233626051-0e6731af-181f-47b9-9079-467b256a00f4.png)

**Comment by kkuepper** [comment]
The first draft of the mini player has been implemented by @ZDerekh but the bigger version still has to be done.

**Comment by Joaveinz** [comment]
What is meant by the first draft @kkuepper @SimonSimCity ?

Is this what I can currently see in the Main branch?

**Comment by Joaveinz** [comment]
Simon just explained to be that what I see now in the main branch is the First Draft 👍

**Comment by Joaveinz** [comment]
@SimonSimCity @kkuepper What is the difference between these two designs of the media player? Has a final design be decided?

<img width="1138" alt="image" src="https://github.com/bcc-code/bmm-web/assets/54300414/8e94536d-5b67-41b0-92e2-b48e8f69c84b">

**Comment by Joaveinz** [comment]
Simon has informed me that we go with the one on the right, as that's the one that he's seen being used more often.

**Comment by Joaveinz** [comment]
@SimonSimCity and @kkuepper  Here's a small update since last week


Closed player:
![image](https://github.com/bcc-code/bmm-web/assets/54300414/7501f900-5821-46f8-8d67-94d94caa2fdf)


On hover:
![image](https://github.com/bcc-code/bmm-web/assets/54300414/982626c4-7c39-41a6-bc74-d610f801e6f3)


Open Player:
![image](https://github.com/bcc-code/bmm-web/assets/54300414/68970b64-6345-4479-a8eb-3afb9805e084)


One thing that I have been struggling with is the slider / player. Maybe there's a library we can use for that?

**Comment by sifferhans** [comment]
> One thing that I have been struggling with is the slider / player. Maybe there's a library we can use for that?

@Joaveinz You can probably just use SVG for the slider 😁 I guess it is a bit difficult if you should be able to drag/click on it though

**Comment by Joaveinz** [comment]
How should we handle extra long titles and subtitles? Right now, every song has a different width
We could set a fixed width for example and then use Ellipsis.


![image](https://github.com/bcc-code/bmm-web/assets/54300414/89a0b39c-4d18-40d3-848a-808c4f3e75c2)
![image](https://github.com/bcc-code/bmm-web/assets/54300414/18f98e83-1bc4-4ebb-9257-d3b22b2c8f90)

**Comment by kkuepper** [comment]
I'm pretty sure @sclausendk wants to have a fixed width with ellipsis.
In the app we animate truncated text to slowly move across the screen, but I think that's too much work on web.

**Comment by Joaveinz** [comment]
Ok, great. I'll see what I can do

**Comment by andreasgangso** [comment]
A volume slider is important when one is trying to balance bmm with other things playing

**Comment by SimonSimCity** [comment]
@sclausendk since what Andreas wrote is not part of the design, I'm awaiting your response on this 🤗 The PR #227, which plans to finish off the design of the player will only include features you considered in the design.

**Comment by SimonSimCity** [comment]
@andreasgangso @sclausendk since what Andreas wrote is not part of the design, I'm awaiting your response on this 🤗 The PR https://github.com/bcc-code/bmm-web/pull/227, which plans to finish off the design of the player will only include features you considered in the design.

**Comment by SimonSimCity** [comment]
The remaining issue has been moved to #305; this issue will therefore be closed.
