### ISSUE TITLE
Profile Dropdown & storing settings

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-web#8]
- see [Figma for how it's supposed to look](https://www.figma.com/file/vUnfD52FdhTmXq4Wjd5ieI/Bmm-Web-2023?node-id=153%3A127572&t=DM37HzaU1nHnnRjR-0).
- The values should be stored in LocalStorage.

Tasks:
- [x] Implement `Feedback`
- [x] Implement `Contact`
- [x] don't implement `About BMM` since it needs to be different. We'll decide exactly how at a later stage (v0.6 or later).
- [x] implement Profile dropdown (Thank you @belljohan3)

Further tasks have been moved into #162

**Comment by sifferhans** [comment]
Should we use something like [Headless UI](https://headlessui.com/vue/menu) for the menu?

**Comment by belljohan3** [comment]
Hi @kkuepper 
Can we do this task with headlessUi as @sifferhans suggested ? Or is there something else ?
Thanks

**Comment by belljohan3** [comment]
@kkuepper i will give a try to pure tailwind first.
